### ISSUE TITLE
Mix Up in ordering of imports

### ISSUE THREAD

**Issue by shemogumbe** [adamsdenniskariuki/Adams-Kariuki-Dojo-Project#4]
- notice your imports in controllers.py file are so mixed up, we cannot tell which ones are from the standard library, which ones are third party apps and which ones are from your application, 
-There are also two empty lines at the beginning of the file. How about you use the pep 8 recommendation for ordering of imports

**Comment by adamsdenniskariuki** [comment]
@andela-sogumbe Updated all files with imports with PEP8 recommendations and removed the empty lines:
1. standard libraries
2. 3rd party libraries
3. Local libraries
