### ISSUE TITLE
Positional arguments used for optional parameters

### ISSUE THREAD

**Issue by shemogumbe** [adamsdenniskariuki/Adams-Kariuki-Dojo-Project#5]
In add_staff method, controllers.py line 118, I notice wants_accomodation is used as a positional argument, does this mean it is a mandatory argument, why is it not used as a positional argument that is supplied a default value

**Comment by adamsdenniskariuki** [comment]
@andela-sogumbe I have updated the add_staff method to make wants_accomodation a keyword argument.
