### ISSUE TITLE
Multiple ways of doing same thing in person.py

### ISSUE THREAD

**Issue by shemogumbe** [adamsdenniskariuki/Adams-Kariuki-Dojo-Project#7]
In person.py file, I see a problem with our implementation of overriding, overriding always makes sense when there is difference in the behavior of a method, in your case, the behavior of the init methods are all the same though it is overridden in the child classes, How about we try something like specifying defaults for person type in staff and fellow classes, wants accommodation in the fellow class and maybe even remove the wants_accommodation attribute from the staff class. Any thoughts?

**Comment by adamsdenniskariuki** [comment]
@andela-sogumbe Thats true. I have specified defaults for person type in the Fellow and Staff Classes and removed the wants accommodation from the Staff class.
