### ISSUE TITLE
The room class allows us to create a room which is not an office or a living space

### ISSUE THREAD

**Issue by shemogumbe** [adamsdenniskariuki/Adams-Kariuki-Dojo-Project#8]
I notice the room class can be instantiated and passed arguments including room type, suppose we pass a room type which is not an office or a living space, the room would still be created, How about we prevent this class from being instantiated and its methods to only be accessible to child classes

**Comment by adamsdenniskariuki** [comment]
@andela-sogumbe Added ABC Meta and an @abstract method which ensures that the Room and Person classes is only accessible to child classes
