### ISSUE TITLE
Class name tat does not make sense in its context of use

### ISSUE THREAD

**Issue by shemogumbe** [adamsdenniskariuki/Adams-Kariuki-Dojo-Project#9]
The class name controllers does not make sense in its sense, real world OOP requires that we name classes based on what they do, it implies class should have attributes and methods that relate to what it's objects in the real world do

**Comment by adamsdenniskariuki** [comment]
@andela-sogumbe Renamed the controllers class to interface because it provides an interface between the view(app.py) and the models
